create table SHASIHIN_ZYOUHOU(
SHAIN_ID VARCHAR(255) not null,
SHAIN_NAME VARCHAR(255),
NENNREI CHAR(4),
SEIBETU VARCHAR(255),
SYASHIN_ID VARCHAR(255),
ZYUUSYO VARCHAR(255),
BUSYO_ID VARCHAR(255),
constraint SYAIN_ZYOUHOU_PKC primary key (SHAIN_ID)
)
;

commit;


